package com.humtrusa.entidades;
// Generated 30/04/2020 17:56:07 by Hibernate Tools 3.5.0.Final

/**
 * FacDetalleComprasId generated by hbm2java
 */
public class FacDetalleComprasId implements java.io.Serializable {

	private long idOrdencompra;
	private long codagenciapedido;
	private long secuencial;

	public FacDetalleComprasId() {
	}

	public FacDetalleComprasId(long idOrdencompra, long codagenciapedido, long secuencial) {
		this.idOrdencompra = idOrdencompra;
		this.codagenciapedido = codagenciapedido;
		this.secuencial = secuencial;
	}

	public long getIdOrdencompra() {
		return this.idOrdencompra;
	}

	public void setIdOrdencompra(long idOrdencompra) {
		this.idOrdencompra = idOrdencompra;
	}

	public long getCodagenciapedido() {
		return this.codagenciapedido;
	}

	public void setCodagenciapedido(long codagenciapedido) {
		this.codagenciapedido = codagenciapedido;
	}

	public long getSecuencial() {
		return this.secuencial;
	}

	public void setSecuencial(long secuencial) {
		this.secuencial = secuencial;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacDetalleComprasId))
			return false;
		FacDetalleComprasId castOther = (FacDetalleComprasId) other;

		return (this.getIdOrdencompra() == castOther.getIdOrdencompra())
				&& (this.getCodagenciapedido() == castOther.getCodagenciapedido())
				&& (this.getSecuencial() == castOther.getSecuencial());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdOrdencompra();
		result = 37 * result + (int) this.getCodagenciapedido();
		result = 37 * result + (int) this.getSecuencial();
		return result;
	}

}
