package com.humtrusa.entidades;
// Generated 04/03/2020 18:22:17 by Hibernate Tools 3.5.0.Final

/**
 * Genagencias generated by hbm2java
 */
public class Genagencias implements java.io.Serializable {

	private GenagenciasId id;

	public Genagencias() {
	}

	public Genagencias(GenagenciasId id) {
		this.id = id;
	}

	public GenagenciasId getId() {
		return this.id;
	}

	public void setId(GenagenciasId id) {
		this.id = id;
	}

}
