package com.humtrusa.entidades;
// Generated 23/02/2020 2:47:59 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * GenempresasId generated by hbm2java
 */
public class GenempresasId implements java.io.Serializable {

	private String codempresa;
	private String nombre;
	private String gerente;
	private String ruccontador;
	private String tipoidreplegal;
	private String idreplegal;
	private String codusuario;
	private Date fecha;
	private String codpais;
	private String hostcorreo;
	private String rucempresa;
	private String tipoidempresa;
	private String escontribuyenteespecial;
	private String numresolucion;
	private String lineagrupoempresarial;

	public GenempresasId() {
	}

	public GenempresasId(String codempresa, String nombre, String gerente, String ruccontador, String tipoidreplegal,
			String idreplegal, String codusuario, Date fecha, String codpais, String hostcorreo, String rucempresa,
			String tipoidempresa, String escontribuyenteespecial, String numresolucion, String lineagrupoempresarial) {
		this.codempresa = codempresa;
		this.nombre = nombre;
		this.gerente = gerente;
		this.ruccontador = ruccontador;
		this.tipoidreplegal = tipoidreplegal;
		this.idreplegal = idreplegal;
		this.codusuario = codusuario;
		this.fecha = fecha;
		this.codpais = codpais;
		this.hostcorreo = hostcorreo;
		this.rucempresa = rucempresa;
		this.tipoidempresa = tipoidempresa;
		this.escontribuyenteespecial = escontribuyenteespecial;
		this.numresolucion = numresolucion;
		this.lineagrupoempresarial = lineagrupoempresarial;
	}

	public String getCodempresa() {
		return this.codempresa;
	}

	public void setCodempresa(String codempresa) {
		this.codempresa = codempresa;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getGerente() {
		return this.gerente;
	}

	public void setGerente(String gerente) {
		this.gerente = gerente;
	}

	public String getRuccontador() {
		return this.ruccontador;
	}

	public void setRuccontador(String ruccontador) {
		this.ruccontador = ruccontador;
	}

	public String getTipoidreplegal() {
		return this.tipoidreplegal;
	}

	public void setTipoidreplegal(String tipoidreplegal) {
		this.tipoidreplegal = tipoidreplegal;
	}

	public String getIdreplegal() {
		return this.idreplegal;
	}

	public void setIdreplegal(String idreplegal) {
		this.idreplegal = idreplegal;
	}

	public String getCodusuario() {
		return this.codusuario;
	}

	public void setCodusuario(String codusuario) {
		this.codusuario = codusuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getCodpais() {
		return this.codpais;
	}

	public void setCodpais(String codpais) {
		this.codpais = codpais;
	}

	public String getHostcorreo() {
		return this.hostcorreo;
	}

	public void setHostcorreo(String hostcorreo) {
		this.hostcorreo = hostcorreo;
	}

	public String getRucempresa() {
		return this.rucempresa;
	}

	public void setRucempresa(String rucempresa) {
		this.rucempresa = rucempresa;
	}

	public String getTipoidempresa() {
		return this.tipoidempresa;
	}

	public void setTipoidempresa(String tipoidempresa) {
		this.tipoidempresa = tipoidempresa;
	}

	public String getEscontribuyenteespecial() {
		return this.escontribuyenteespecial;
	}

	public void setEscontribuyenteespecial(String escontribuyenteespecial) {
		this.escontribuyenteespecial = escontribuyenteespecial;
	}

	public String getNumresolucion() {
		return this.numresolucion;
	}

	public void setNumresolucion(String numresolucion) {
		this.numresolucion = numresolucion;
	}

	public String getLineagrupoempresarial() {
		return this.lineagrupoempresarial;
	}

	public void setLineagrupoempresarial(String lineagrupoempresarial) {
		this.lineagrupoempresarial = lineagrupoempresarial;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GenempresasId))
			return false;
		GenempresasId castOther = (GenempresasId) other;

		return ((this.getCodempresa() == castOther.getCodempresa()) || (this.getCodempresa() != null
				&& castOther.getCodempresa() != null && this.getCodempresa().equals(castOther.getCodempresa())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getGerente() == castOther.getGerente()) || (this.getGerente() != null
						&& castOther.getGerente() != null && this.getGerente().equals(castOther.getGerente())))
				&& ((this.getRuccontador() == castOther.getRuccontador())
						|| (this.getRuccontador() != null && castOther.getRuccontador() != null
								&& this.getRuccontador().equals(castOther.getRuccontador())))
				&& ((this.getTipoidreplegal() == castOther.getTipoidreplegal())
						|| (this.getTipoidreplegal() != null && castOther.getTipoidreplegal() != null
								&& this.getTipoidreplegal().equals(castOther.getTipoidreplegal())))
				&& ((this.getIdreplegal() == castOther.getIdreplegal()) || (this.getIdreplegal() != null
						&& castOther.getIdreplegal() != null && this.getIdreplegal().equals(castOther.getIdreplegal())))
				&& ((this.getCodusuario() == castOther.getCodusuario()) || (this.getCodusuario() != null
						&& castOther.getCodusuario() != null && this.getCodusuario().equals(castOther.getCodusuario())))
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())))
				&& ((this.getCodpais() == castOther.getCodpais()) || (this.getCodpais() != null
						&& castOther.getCodpais() != null && this.getCodpais().equals(castOther.getCodpais())))
				&& ((this.getHostcorreo() == castOther.getHostcorreo()) || (this.getHostcorreo() != null
						&& castOther.getHostcorreo() != null && this.getHostcorreo().equals(castOther.getHostcorreo())))
				&& ((this.getRucempresa() == castOther.getRucempresa()) || (this.getRucempresa() != null
						&& castOther.getRucempresa() != null && this.getRucempresa().equals(castOther.getRucempresa())))
				&& ((this.getTipoidempresa() == castOther.getTipoidempresa())
						|| (this.getTipoidempresa() != null && castOther.getTipoidempresa() != null
								&& this.getTipoidempresa().equals(castOther.getTipoidempresa())))
				&& ((this.getEscontribuyenteespecial() == castOther.getEscontribuyenteespecial())
						|| (this.getEscontribuyenteespecial() != null && castOther.getEscontribuyenteespecial() != null
								&& this.getEscontribuyenteespecial().equals(castOther.getEscontribuyenteespecial())))
				&& ((this.getNumresolucion() == castOther.getNumresolucion())
						|| (this.getNumresolucion() != null && castOther.getNumresolucion() != null
								&& this.getNumresolucion().equals(castOther.getNumresolucion())))
				&& ((this.getLineagrupoempresarial() == castOther.getLineagrupoempresarial())
						|| (this.getLineagrupoempresarial() != null && castOther.getLineagrupoempresarial() != null
								&& this.getLineagrupoempresarial().equals(castOther.getLineagrupoempresarial())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodempresa() == null ? 0 : this.getCodempresa().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getGerente() == null ? 0 : this.getGerente().hashCode());
		result = 37 * result + (getRuccontador() == null ? 0 : this.getRuccontador().hashCode());
		result = 37 * result + (getTipoidreplegal() == null ? 0 : this.getTipoidreplegal().hashCode());
		result = 37 * result + (getIdreplegal() == null ? 0 : this.getIdreplegal().hashCode());
		result = 37 * result + (getCodusuario() == null ? 0 : this.getCodusuario().hashCode());
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + (getCodpais() == null ? 0 : this.getCodpais().hashCode());
		result = 37 * result + (getHostcorreo() == null ? 0 : this.getHostcorreo().hashCode());
		result = 37 * result + (getRucempresa() == null ? 0 : this.getRucempresa().hashCode());
		result = 37 * result + (getTipoidempresa() == null ? 0 : this.getTipoidempresa().hashCode());
		result = 37 * result
				+ (getEscontribuyenteespecial() == null ? 0 : this.getEscontribuyenteespecial().hashCode());
		result = 37 * result + (getNumresolucion() == null ? 0 : this.getNumresolucion().hashCode());
		result = 37 * result + (getLineagrupoempresarial() == null ? 0 : this.getLineagrupoempresarial().hashCode());
		return result;
	}

}
