package com.humtrusa.entidades;
// Generated 20/03/2020 14:36:48 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Genperfiles generated by hbm2java
 */
public class Genperfiles implements java.io.Serializable {

	private Long codperfil;
	private Genusuarios genusuarios;
	private Genestados genestados;
	private Genempresas genempresas;
	private String descripcion;
	private Date fecha;
	private String usariocambioestado;
	private Date fechacambioestado;
	private Set permisosxperfils = new HashSet(0);
	private Set usuariosxagencias = new HashSet(0);

	public Genperfiles() {
	}

	public Genperfiles(Genusuarios genusuarios, Genestados genestados, Genempresas genempresas, String descripcion,
			Date fecha, String usariocambioestado, Date fechacambioestado, Set permisosxperfils,
			Set usuariosxagencias) {
		this.genusuarios = genusuarios;
		this.genestados = genestados;
		this.genempresas = genempresas;
		this.descripcion = descripcion;
		this.fecha = fecha;
		this.usariocambioestado = usariocambioestado;
		this.fechacambioestado = fechacambioestado;
		this.permisosxperfils = permisosxperfils;
		this.usuariosxagencias = usuariosxagencias;
	}

	public Long getCodperfil() {
		return this.codperfil;
	}

	public void setCodperfil(Long codperfil) {
		this.codperfil = codperfil;
	}

	public Genusuarios getGenusuarios() {
		return this.genusuarios;
	}

	public void setGenusuarios(Genusuarios genusuarios) {
		this.genusuarios = genusuarios;
	}

	public Genestados getGenestados() {
		return this.genestados;
	}

	public void setGenestados(Genestados genestados) {
		this.genestados = genestados;
	}

	public Genempresas getGenempresas() {
		return this.genempresas;
	}

	public void setGenempresas(Genempresas genempresas) {
		this.genempresas = genempresas;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getUsariocambioestado() {
		return this.usariocambioestado;
	}

	public void setUsariocambioestado(String usariocambioestado) {
		this.usariocambioestado = usariocambioestado;
	}

	public Date getFechacambioestado() {
		return this.fechacambioestado;
	}

	public void setFechacambioestado(Date fechacambioestado) {
		this.fechacambioestado = fechacambioestado;
	}

	public Set getPermisosxperfils() {
		return this.permisosxperfils;
	}

	public void setPermisosxperfils(Set permisosxperfils) {
		this.permisosxperfils = permisosxperfils;
	}

	public Set getUsuariosxagencias() {
		return this.usuariosxagencias;
	}

	public void setUsuariosxagencias(Set usuariosxagencias) {
		this.usuariosxagencias = usuariosxagencias;
	}

}
