package com.humtrusa.entidades;
// Generated 25/02/2020 21:11:45 by Hibernate Tools 3.5.0.Final

/**
 * Genrecursos generated by hbm2java
 */
public class Genrecursos implements java.io.Serializable {

	private GenrecursosId id;
	private Genopciones genopciones;
	private String tipo;
	private String url;

	public Genrecursos() {
	}

	public Genrecursos(GenrecursosId id, Genopciones genopciones, String tipo, String url) {
		this.id = id;
		this.genopciones = genopciones;
		this.tipo = tipo;
		this.url = url;
	}

	public GenrecursosId getId() {
		return this.id;
	}

	public void setId(GenrecursosId id) {
		this.id = id;
	}

	public Genopciones getGenopciones() {
		return this.genopciones;
	}

	public void setGenopciones(Genopciones genopciones) {
		this.genopciones = genopciones;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
