package com.humtrusa.entidades;
// Generated 30/04/2020 17:56:07 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Invstock generated by hbm2java
 */
public class Invstock implements java.io.Serializable {

	private InvstockId id;
	private Bodegasxagencias bodegasxagencias;
	private Genarticulos genarticulos;
	private Long codalterno;
	private Double cantidadDisponible;
	private Double cantidadMin;
	private Double cantidadMax;
	private Date fechaultingreso;
	private Date fechaultegreso;

	public Invstock() {
	}

	public Invstock(InvstockId id, Bodegasxagencias bodegasxagencias, Genarticulos genarticulos) {
		this.id = id;
		this.bodegasxagencias = bodegasxagencias;
		this.genarticulos = genarticulos;
	}

	public Invstock(InvstockId id, Bodegasxagencias bodegasxagencias, Genarticulos genarticulos, Long codalterno,
			Double cantidadDisponible, Double cantidadMin, Double cantidadMax, Date fechaultingreso,
			Date fechaultegreso) {
		this.id = id;
		this.bodegasxagencias = bodegasxagencias;
		this.genarticulos = genarticulos;
		this.codalterno = codalterno;
		this.cantidadDisponible = cantidadDisponible;
		this.cantidadMin = cantidadMin;
		this.cantidadMax = cantidadMax;
		this.fechaultingreso = fechaultingreso;
		this.fechaultegreso = fechaultegreso;
	}

	public InvstockId getId() {
		return this.id;
	}

	public void setId(InvstockId id) {
		this.id = id;
	}

	public Bodegasxagencias getBodegasxagencias() {
		return this.bodegasxagencias;
	}

	public void setBodegasxagencias(Bodegasxagencias bodegasxagencias) {
		this.bodegasxagencias = bodegasxagencias;
	}

	public Genarticulos getGenarticulos() {
		return this.genarticulos;
	}

	public void setGenarticulos(Genarticulos genarticulos) {
		this.genarticulos = genarticulos;
	}

	public Long getCodalterno() {
		return this.codalterno;
	}

	public void setCodalterno(Long codalterno) {
		this.codalterno = codalterno;
	}

	public Double getCantidadDisponible() {
		return this.cantidadDisponible;
	}

	public void setCantidadDisponible(Double cantidadDisponible) {
		this.cantidadDisponible = cantidadDisponible;
	}

	public Double getCantidadMin() {
		return this.cantidadMin;
	}

	public void setCantidadMin(Double cantidadMin) {
		this.cantidadMin = cantidadMin;
	}

	public Double getCantidadMax() {
		return this.cantidadMax;
	}

	public void setCantidadMax(Double cantidadMax) {
		this.cantidadMax = cantidadMax;
	}

	public Date getFechaultingreso() {
		return this.fechaultingreso;
	}

	public void setFechaultingreso(Date fechaultingreso) {
		this.fechaultingreso = fechaultingreso;
	}

	public Date getFechaultegreso() {
		return this.fechaultegreso;
	}

	public void setFechaultegreso(Date fechaultegreso) {
		this.fechaultegreso = fechaultegreso;
	}

}
