package com.humtrusa.entidades;
// Generated 02/05/2020 8:22:47 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Genbodegas generated by hbm2java
 */
public class Genbodegas implements java.io.Serializable {

	private Long codbodega;
	private Genusuarios genusuarios;
	private Gentipobodegas gentipobodegas;
	private Long codestado;
	private String descripcion;
	private String ubicacion;
	private Date fecharegistro;
	private Set bodegasxagenciases = new HashSet(0);

	public Genbodegas() {
	}

	public Genbodegas(Genusuarios genusuarios, Gentipobodegas gentipobodegas, Long codestado, String descripcion,
			String ubicacion, Date fecharegistro, Set bodegasxagenciases) {
		this.genusuarios = genusuarios;
		this.gentipobodegas = gentipobodegas;
		this.codestado = codestado;
		this.descripcion = descripcion;
		this.ubicacion = ubicacion;
		this.fecharegistro = fecharegistro;
		this.bodegasxagenciases = bodegasxagenciases;
	}

	public Long getCodbodega() {
		return this.codbodega;
	}

	public void setCodbodega(Long codbodega) {
		this.codbodega = codbodega;
	}

	public Genusuarios getGenusuarios() {
		return this.genusuarios;
	}

	public void setGenusuarios(Genusuarios genusuarios) {
		this.genusuarios = genusuarios;
	}

	public Gentipobodegas getGentipobodegas() {
		return this.gentipobodegas;
	}

	public void setGentipobodegas(Gentipobodegas gentipobodegas) {
		this.gentipobodegas = gentipobodegas;
	}

	public Long getCodestado() {
		return this.codestado;
	}

	public void setCodestado(Long codestado) {
		this.codestado = codestado;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	public Set getBodegasxagenciases() {
		return this.bodegasxagenciases;
	}

	public void setBodegasxagenciases(Set bodegasxagenciases) {
		this.bodegasxagenciases = bodegasxagenciases;
	}

}
