package com.humtrusa.entidades;
// Generated 02/05/2020 8:22:47 by Hibernate Tools 3.5.0.Final

/**
 * Genconsultas generated by hbm2java
 */
public class Genconsultas implements java.io.Serializable {

	private GenconsultasId id;

	public Genconsultas() {
	}

	public Genconsultas(GenconsultasId id) {
		this.id = id;
	}

	public GenconsultasId getId() {
		return this.id;
	}

	public void setId(GenconsultasId id) {
		this.id = id;
	}

}
