package com.humtrusa.entidades;
// Generated 02/05/2020 8:22:47 by Hibernate Tools 3.5.0.Final

/**
 * GenconsultasId generated by hbm2java
 */
public class GenconsultasId implements java.io.Serializable {

	private String codcoleccion;
	private String descripcion;
	private String campocodigo;
	private String campodescripcion;
	private String tipoquery;
	private String query;
	private String parametros;
	private String modo;
	private String datoslocales;

	public GenconsultasId() {
	}

	public GenconsultasId(String codcoleccion, String descripcion, String campocodigo, String campodescripcion,
			String tipoquery, String query, String parametros, String modo, String datoslocales) {
		this.codcoleccion = codcoleccion;
		this.descripcion = descripcion;
		this.campocodigo = campocodigo;
		this.campodescripcion = campodescripcion;
		this.tipoquery = tipoquery;
		this.query = query;
		this.parametros = parametros;
		this.modo = modo;
		this.datoslocales = datoslocales;
	}

	public String getCodcoleccion() {
		return this.codcoleccion;
	}

	public void setCodcoleccion(String codcoleccion) {
		this.codcoleccion = codcoleccion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCampocodigo() {
		return this.campocodigo;
	}

	public void setCampocodigo(String campocodigo) {
		this.campocodigo = campocodigo;
	}

	public String getCampodescripcion() {
		return this.campodescripcion;
	}

	public void setCampodescripcion(String campodescripcion) {
		this.campodescripcion = campodescripcion;
	}

	public String getTipoquery() {
		return this.tipoquery;
	}

	public void setTipoquery(String tipoquery) {
		this.tipoquery = tipoquery;
	}

	public String getQuery() {
		return this.query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public String getParametros() {
		return this.parametros;
	}

	public void setParametros(String parametros) {
		this.parametros = parametros;
	}

	public String getModo() {
		return this.modo;
	}

	public void setModo(String modo) {
		this.modo = modo;
	}

	public String getDatoslocales() {
		return this.datoslocales;
	}

	public void setDatoslocales(String datoslocales) {
		this.datoslocales = datoslocales;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GenconsultasId))
			return false;
		GenconsultasId castOther = (GenconsultasId) other;

		return ((this.getCodcoleccion() == castOther.getCodcoleccion()) || (this.getCodcoleccion() != null
				&& castOther.getCodcoleccion() != null && this.getCodcoleccion().equals(castOther.getCodcoleccion())))
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getCampocodigo() == castOther.getCampocodigo())
						|| (this.getCampocodigo() != null && castOther.getCampocodigo() != null
								&& this.getCampocodigo().equals(castOther.getCampocodigo())))
				&& ((this.getCampodescripcion() == castOther.getCampodescripcion())
						|| (this.getCampodescripcion() != null && castOther.getCampodescripcion() != null
								&& this.getCampodescripcion().equals(castOther.getCampodescripcion())))
				&& ((this.getTipoquery() == castOther.getTipoquery()) || (this.getTipoquery() != null
						&& castOther.getTipoquery() != null && this.getTipoquery().equals(castOther.getTipoquery())))
				&& ((this.getQuery() == castOther.getQuery()) || (this.getQuery() != null
						&& castOther.getQuery() != null && this.getQuery().equals(castOther.getQuery())))
				&& ((this.getParametros() == castOther.getParametros()) || (this.getParametros() != null
						&& castOther.getParametros() != null && this.getParametros().equals(castOther.getParametros())))
				&& ((this.getModo() == castOther.getModo()) || (this.getModo() != null && castOther.getModo() != null
						&& this.getModo().equals(castOther.getModo())))
				&& ((this.getDatoslocales() == castOther.getDatoslocales())
						|| (this.getDatoslocales() != null && castOther.getDatoslocales() != null
								&& this.getDatoslocales().equals(castOther.getDatoslocales())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodcoleccion() == null ? 0 : this.getCodcoleccion().hashCode());
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + (getCampocodigo() == null ? 0 : this.getCampocodigo().hashCode());
		result = 37 * result + (getCampodescripcion() == null ? 0 : this.getCampodescripcion().hashCode());
		result = 37 * result + (getTipoquery() == null ? 0 : this.getTipoquery().hashCode());
		result = 37 * result + (getQuery() == null ? 0 : this.getQuery().hashCode());
		result = 37 * result + (getParametros() == null ? 0 : this.getParametros().hashCode());
		result = 37 * result + (getModo() == null ? 0 : this.getModo().hashCode());
		result = 37 * result + (getDatoslocales() == null ? 0 : this.getDatoslocales().hashCode());
		return result;
	}

}
