package com.humtrusa.entidades;
// Generated 02/05/2020 8:22:47 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Gentipopagos generated by hbm2java
 */
public class Gentipopagos implements java.io.Serializable {

	private Long codtipopago;
	private String descripcion;
	private String codusuario;
	private Date fecha;
	private Set facOrdenesCompras = new HashSet(0);

	public Gentipopagos() {
	}

	public Gentipopagos(String descripcion, String codusuario, Date fecha) {
		this.descripcion = descripcion;
		this.codusuario = codusuario;
		this.fecha = fecha;
	}

	public Gentipopagos(String descripcion, String codusuario, Date fecha, Set facOrdenesCompras) {
		this.descripcion = descripcion;
		this.codusuario = codusuario;
		this.fecha = fecha;
		this.facOrdenesCompras = facOrdenesCompras;
	}

	public Long getCodtipopago() {
		return this.codtipopago;
	}

	public void setCodtipopago(Long codtipopago) {
		this.codtipopago = codtipopago;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCodusuario() {
		return this.codusuario;
	}

	public void setCodusuario(String codusuario) {
		this.codusuario = codusuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set getFacOrdenesCompras() {
		return this.facOrdenesCompras;
	}

	public void setFacOrdenesCompras(Set facOrdenesCompras) {
		this.facOrdenesCompras = facOrdenesCompras;
	}

}
