package com.humtrusa.entidades;
// Generated 02/05/2020 8:22:47 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Gentipobodegas generated by hbm2java
 */
public class Gentipobodegas implements java.io.Serializable {

	private Long idtipobodega;
	private String descripcion;
	private String codusuario;
	private Date fecha;
	private Set genbodegases = new HashSet(0);

	public Gentipobodegas() {
	}

	public Gentipobodegas(String descripcion, String codusuario, Date fecha, Set genbodegases) {
		this.descripcion = descripcion;
		this.codusuario = codusuario;
		this.fecha = fecha;
		this.genbodegases = genbodegases;
	}

	public Long getIdtipobodega() {
		return this.idtipobodega;
	}

	public void setIdtipobodega(Long idtipobodega) {
		this.idtipobodega = idtipobodega;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCodusuario() {
		return this.codusuario;
	}

	public void setCodusuario(String codusuario) {
		this.codusuario = codusuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set getGenbodegases() {
		return this.genbodegases;
	}

	public void setGenbodegases(Set genbodegases) {
		this.genbodegases = genbodegases;
	}

}
