package com.humtrusa.entidades;
// Generated 02/05/2020 8:22:47 by Hibernate Tools 3.5.0.Final

/**
 * Permisosxusuario generated by hbm2java
 */
public class Permisosxusuario implements java.io.Serializable {

	private PermisosxusuarioId id;

	public Permisosxusuario() {
	}

	public Permisosxusuario(PermisosxusuarioId id) {
		this.id = id;
	}

	public PermisosxusuarioId getId() {
		return this.id;
	}

	public void setId(PermisosxusuarioId id) {
		this.id = id;
	}

}
